apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern
spec:
  type: NodePort                    # 서비스 타입을 NodePort로 변경
  ports:
  - name: backend-port
    port: 3500                        # 클러스터 내부에서 사용할 포트
    targetPort: 3500                # 컨테이너에서 사용할 포트
    nodePort: 31001                 # 외부에서 접근할 포트 (원하는 포트로 변경 가능)
    protocol: TCP
  selector:
    role: backend

